print("==============================") 
print("= NAMA    : Risky HariAdi     ") 
print("= NIM     : 312010124         ")
print("= KELAS   : TI.20 A.1         ") 
print("==============================") 


print("Please enter your full name : Risky HariAdi") 
fullname=input() 
print("Please enter nickname : Risky") 
nickname=input() 
print("Please enter your NPM : 312010124") 
npm=input() 
print("Please enter place of birth : BEKASI") 
pob=input() 
print("Please enter date of birth : 13") 
date=input() 
print("Please enter your month of birth : July") 
month=input() 
print("Please enter year of birth : 2000") 
year=input() 
print("Please enter your phone number : 085282024179")
phone=input() 
print("Please enter your address : Perumahan Graha Bagasasi") 
address=input() 

dob=input("2020-year")

print("\n\n Assalamu'alaikum. ")
print("f\n Let me introduce my self, my name is {Risky HariAdi}, but you can call me {Risky}, my NPM {312010124}, I was born in {BEKASI} and iam {2020} years old, I am very glad if you want to invite my house in {Perumahan Graha Bagasasi}, So don't forget to call me before with the number {085282024179}, \n\n Thanks you very much ")

